base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.base, name = 'base'),
    path('about', views.about, name= 'about'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('works/', include('works.urls')),
    path('contact/', include('contact.urls')),
]

works/urls.py
from django.urls import path
from . import views

app_name = 'works'

urlpatterns = [
    path('', views.works, name='works'),
    path('<int:works_id>/', views.work, name='work'),
]

base/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

class Contact(models.Model):
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=150)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

works/models.py
from django.db import models

class Work(models.Model):
    imagesrc = models.ImageField(upload_to='static/works/')
    url = models.URLField(blank=True)
    flag = models.BooleanField(blank=True)
    titleno = models.CharField(max_length=10)
    title = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.title

contact/forms.py
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['email', 'subject', 'message']

base/views.py
from django.shortcuts import render

def base(request):
    return render(request, 'base/base.html')

def about(request):
    return render(request, 'base/about.html') 
       

contact/views.py
from django.shortcuts import render
from .forms import ContactForm


def contact(request):
    if request.method == 'GET':
        return render(request, 'contact/contact.html', {'form': ContactForm()})
    else:
        try:
            form = ContactForm(request.POST)
            form.save()
            return render(request, 'contact/contact.html', {'form': ContactForm(), 'info': 'Data Captured'})
        except ValueError:
            return render(request, 'contact/contact.html', {'form': ContactForm(), 'info': 'Error generated, Please try again'})
  

works/views.py
from django.shortcuts import render, get_object_or_404
from .models import Work

def works(request):
    works = Work.objects.all()
    return render(request, 'works/works.html', {'works': works})

def work(request, works_id):
    work = get_object_or_404(Work, pk = works_id)
    return render(request, 'works/work.html', {'work': work})    

base/templates/base/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

  <title>Rishabh Shukla</title>

  <link href="{% static 'base/main.3f6952e4.css' %}" rel="stylesheet">

</head>

<body class="">
  <div id="site-border-left"></div>
  <div id="site-border-right"></div>
  <div id="site-border-top"></div>
  <div id="site-border-bottom"></div>
  <!-- Add your content of header -->
  <header>
    <nav class="navbar  navbar-fixed-top navbar-default">
      <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav ">
            <li><a href=".." title="">01 : Home</a></li>
            <li><a href="./works" title="">02 : Works</a></li>
            <li><a href="./about" title="">03 : About me</a></li>
            <li><a href="./contact" title="">04 : Contact</a></li>
            <li><a href="{% static 'base/Resume.pdf' %}" target="_blank" rel="noopener noreferrer" title="">05 : Resume</a></li>
          </ul>


        </div>
      </div>
    </nav>
  </header>

  <div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">03 : About me</h1>
          </div>

          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <h3>Origin</h3>
                  <p>I was born and raised in northern India and have been dwelling around this region for the past few
                    decades.</p>
                  <h3>Interests </h3>
                  <p>A tad bit of computer science sprinkled with travelling, music and gaming in small doses.</p>
                  <h3>Philosophy</h3>
                  <p>I belive in being calm and composed when things get out of hand. If something unexpected
                    gives you pleasure it is probably worth checking out. Also, if you are still reading with font this small, I
                    commend you.</p>
                </div>
                <div class="col-xs-12 col-md-6">
                  <img src="{% static 'base/profileblack.jpg' %}" class="img-responsive" alt="">
                </div>
              </div>
            </div>
          </div>


        </div>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function (event) {
      navActivePage();
    });
  </script>

  <script type="text/javascript" src="{% static 'base/main.70a66962.js' %}"></script>

</body>

</html>

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

  <title>Rishabh Shukla</title>

  <link href="{% static 'base/main.3f6952e4.css' %}" rel="stylesheet">
</head>

<body class="minimal">
  <div id="site-border-left"></div>
  <div id="site-border-right"></div>
  <div id="site-border-top"></div>
  <div id="site-border-bottom"></div>
  <!-- Add your content of header -->
  <header>
    <nav class="navbar  navbar-fixed-top navbar-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav ">
            <li><a href="" title="">01 : Home</a></li>
            <li><a href="./works" title="">02 : Works</a></li>
            <li><a href="./about" title="">03 : About me</a></li>
            <li><a href="./contact" title="">04 : Contact</a></li>
            <li><a href="{% static 'base/Resume.pdf' %}" target="_blank" rel="noopener noreferrer" title="">05 : Resume</a></li>
          </ul>


        </div>
      </div>
    </nav>
  </header>
  <!-- Add your site or app content here -->
  <div class="hero-full-container background-image-container white-text-container"
    style="background-image: linear-gradient(to top, rgba(0,0,0,0.6), rgba(0,0,0,1)),url('./static/base/bgblack.jpg')">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="hero-full-wrapper">
            <div class="text-content">
              <h1>Hello,<br>
                <span id="typed-strings">
                  <span>I'm Rishabh Shukla</span>
                  <span>Python enthusiast</span>
                  <span>Glad to have you here!</span>
                </span>
                <span id="typed"></span>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function (event) {
      type();
      movingBackgroundImage();
    });
  </script>


  <script type="text/javascript" src="{% static 'base/main.70a66962.js' %}"></script>

</body>

</html>

contact/templates/contact/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

  <title>Rishabh Shukla</title>  

<link href="{% static 'base/main.3f6952e4.css' %}" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href=".." title="">01 : Home</a></li>
          <li><a href="../works" title="">02 : Works</a></li>
          <li><a href="../about" title="">03 : About me</a></li>
          <li><a href="" title="">04 : Contact</a></li>
          <li><a href="{% static 'base/Resume.pdf' %}" target="_blank" rel="noopener noreferrer" title="">05 : Resume</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">04 : Contact me</h1>
          </div>
          {% if info %}
          <div class="section-container-spacer text-center">
            <h1 class="h2">{{ info }}</h1>
          </div>
          {% endif %}
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
               <form action="" class="reveal-content" method="POST">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-7">
                      <div class="form-group">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required>
                      </div>
                      <div class="form-group">
                        <textarea class="form-control" rows="5" name="message" placeholder="Enter your message" required></textarea>
                      </div>
                      <button type="submit" class="btn btn-default btn-lg">Send</button>
                    </div>
                    <div class="col-md-5 address-container">
                      <ul class="list-unstyled">
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa-at" aria-hidden="true"></i>
                          </span>
                          rishabhshukla97@gmail.com
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa fa-map-marker" aria-hidden="true"></i>
                          </span>
                          India
                        </li>
                      </ul>
                      <h3>Follow me on these networks</h3>
                      <a href="https://github.com/developer-47/" target="_blank" rel="noopener noreferrer" title="" class="fa-icon">
                        <i class="fa fa-github"></i>
                      </a>
                      <a href="https://www.linkedin.com/in/rishabh-shukla-943002133/" target="_blank" rel="noopener noreferrer" title="" class="fa-icon">
                        <i class="fa fa-linkedin"></i>
                      </a>
                      <a href="https://twitter.com/SimpletonNormie/" target="_blank" rel="noopener noreferrer" title="" class="fa-icon">
                        <i class="fa fa-twitter"></i>
                      </a>
                      <a href="https://www.reddit.com/user/DhartiPeBojh/" target="_blank" rel="noopener noreferrer" title="" class="fa-icon">
                        <i class="fa fa-reddit"></i>
                      </a>

                    </div>
                  </div>
                </form>
            </div>

          </div>
         
       </div>
      </div>
    </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

<script type="text/javascript" src="{% static 'base/main.70a66962.js' %}"></script>

</body>

</html>

works/templates/works/work.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

  <title>Rishabh Shukla</title>  

<link href="{% static 'base/main.3f6952e4.css' %}" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="../.." title="">01 : Home</a></li>
          <li><a href=".." title="">02 : Works</a></li>
          <li><a href="../../about" title="">03 : About me</a></li>
          <li><a href="../../contact" title="">04 : Contact</a></li>
          <li><a href="{% static 'base/Resume.pdf' %}" target="_blank" rel="noopener noreferrer" title="">05 : Resume</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>
<div class="section-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <img src="{{ work.imagesrc.url }}" class="img-responsive" alt="">
        <div class="card-container">
          <div class="text-center">
            <h1 class="h2">{{ work.titleno }} : {{ work.title }}</h1>
          </div>
          <p>{{ work.description|safe }}</p>
          <blockquote>
            <small class="pull-right">Rishabh Shukla</small>
          </blockquote>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

<script type="text/javascript" src="{% static 'base/main.70a66962.js' %}"></script>


</html>

works/templates/works/works.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

  <title>Rishabh Shukla</title>  

<link href="{% static 'base/main.3f6952e4.css' %}" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href=".." title="">01 : Home</a></li>
          <li><a href="" title="">02 : Works</a></li>
          <li><a href="../about" title="">03 : About me</a></li>
          <li><a href="../contact" title="">04 : Contact</a></li>
          <li><a href="{% static 'base/Resume.pdf' %}" target="_blank" rel="noopener noreferrer" title="">05 : Resume</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
  <div class="container">
    <div class="row">
      
      <div class="col-sm-8 col-sm-offset-2 section-container-spacer">
        <div class="text-center">
          <h1 class="h2">02 : Works</h1>
          <p>Below you can find some of my works. Feel free to contact me ragarding any feedback or suggestions</p>
        </div>
      </div>

      <div class="col-md-12">
     
      <div id="myCarousel" class="carousel slide projects-carousel">
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="row">
                    {% for work in works %}

                    {% if work.flag %} <!---Flag is added for created new bootstrap row (for carousel to function properly)--->
                      </div>
                    </div>
                    <div class="item">
                        <div class="row">
                    
                    {% endif %}

                    <div class="col-sm-4">
                      <a href="{% url 'works:work' work.id %}" title="" class="black-image-project-hover">
                        <img src="{{ work.imagesrc.url }}" alt="" class="img-responsive">
                      </a>
                      <div class="card-container card-container-lg">
                        <h4>{{ work.titleno }}/00{{ works.count }}</h4>
                        <h3>{{ work.title }}</h3>
                        <p>{{ work.description|striptags|truncatechars:100 }}</p>
                        <a href="{% url 'works:work' work.id %}" title="" class="btn btn-default">Discover</a>
                      </div>
                    </div>    
                    {% endfor %}
                </div>
                <!--/row-->
  
            </div>
            <!--/item-->

        </div>
        <!--/carousel-inner--> 
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>

        <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
     </div>



    <!--/myCarousel-->
    </div>



    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

<script type="text/javascript" src="{% static 'base/main.70a66962.js' %}"></script>

</body>

</html>